FROM golang:1.16 AS builder
WORKDIR /go/src/app
COPY ./app /go/src/app
RUN go mod vendor
RUN CGO_ENABLED=1 GOOS=linux go build --ldflags "-extldflags -static" -a -installsuffix cgo -o app .

FROM scratch
#RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY ./app /root
COPY --from=builder /go/src/app/app ./
CMD ["./app"]
